name: Crawling
version: '5.3.0'
main: me.arthed.crawling.Crawling
api-version: 1.17
softdepend: [ WorldGuard ]
authors: [ Arthed ]
description: Improves the crawling mechanic in minecraft!
commands:
  crawling:
    description: Main command for Crawling
    aliases: [crawl]
